spring:
  application.name: stock-price
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
server:
  port: 8080
  servlet:
    context-path: "/stock-price"
project:
  version: "@project.version@"
  description: "@project.description@"
springdoc:
  packages-to-scan:
    - "br.com.fabri.api.controller"
